name: Run Checkmarx SAST Script

on:
  workflow_dispatch
    
jobs:
  run_script:
    runs-on: self-hosted
    steps:
    #- uses: actions/checkout@v3

    # Zip repo
    #- name: Zip Repo
    #  run: |
    #    $file=Get-ChildItem -Path . -Exclude ".git/*"
    #    Compress-Archive -Path $file -DestinationPath checkmarx-upload.zip
    
    # Run local script
    #- name: Run Checkmarx SAST Script
    #  run: python3 C:\dev\repos\Cybersecurity\OSS-Checkmarx-Scans\oss-checkmarx-scan.py ${{github.repository}}
    - name: Run Checkmarx SAST Script
      run: python3 C:\dev\repos\Cybersecurity\OSS-Checkmarx-Scans\scan-with-cxflow.py ${{github.repository}}
    
    # Upload the Report for CodeQL/Security Alerts
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: cx.sarif
