name: Run Checkmarx SAST Script

on:
  workflow_dispatch
    
jobs:
  run_script:
    runs-on: self-hosted
    steps:
    # Run local script
    - name: Run Checkmarx SAST Script
      run: python3 C:\dev\repos\Cybersecurity\OSS-Checkmarx-Scans\oss-checkmarx-scan.py
