name: Run Checkmarx SAST Script

on:
  workflow_dispatch
    
jobs:
  run_script:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    # Zip repo
    - name: Zip Repo
      run: zip -r ${{github.repository}}.zip ${{github.repository}} -x ".git/*" ".github/*"
    
    # Run local script
    - name: Run Checkmarx SAST Script
      run: python3 C:\dev\repos\Cybersecurity\OSS-Checkmarx-Scans\oss-checkmarx-scan.py ${{github.repository}}
